
name = "admin-dashboard-pro"
pages_build_output_dir = "dist"
compatibility_date = "2024-04-01"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "admin-db"
database_id = "be77ebc6-1d0e-4378-8f1b-f13e572ef145"

# KV Namespace Binding
[[kv_namespaces]]
binding = "ADMIN_KV"
id = "44b4e9e9ccb540cca922e2050780ff53"
